feat(scripts): add flag parsing to shell script template

diff --git a/scripts/vx b/scripts/vx
--- a/scripts/vx
+++ b/scripts/vx
@@ -32,6 +32,9 @@ Parameters:
   \\\$1: <++>
   [\\\$1]: <++>
 
+Flags:
+  -<++>
+
 Example:
   $ $FILE <++>
 $(printf EOF)
@@ -39,6 +42,14 @@ $(printf EOF)
 fi
 
 hash <++> || exit 127
+
+while getopts ":<++>:" opt; do
+  case "\$opt" in
+    <++>) ="\$OPTARG";;
+    :) printf '%s\n' "error: -\$OPTARG requires an argument" >&2; exit 2 ;;
+ esac
+done
+shift \$((OPTIND - 1))
 
 EOF
 }
